---
title: "resazurin_analysis"
author: "Samuel Gurr"
date: "2026-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# SET WORKING DIRECTORY 
knitr::opts_knit$set(root.dir = "C:/Users/gurrs/Documents/6_Github_repositories/GurrLab/Resazurin_Pacific_oysters/RAnalysis") # Sam's
#knitr::opts_knit$set(root.dir = "C:/Users/samuel.gurr/Documents/Github_repositories/EAD-ASEB-Airradians_Popgen_OA/") # Sam's
```


```{r}
library(readxl)
library(stringr)
library(pracma)
library(ggplot2)
library(ggpubr)
```

```{r}

metadata_counts <- read.csv("Data/metadata_larvae_counts.csv", sep=',')
View(metadata_counts)

plate_notes <- metadata_counts %>%  dplyr::select(c('PlateID','Well','Note','X')) %>% dplyr::rename(obs_volume = X)
```

```{r}
resaz_72hpf_filenames <- list.files("Data/20260320_72hpf/", pattern = "\\.xlsx$", full.names = TRUE)
resaz_72hpf_filenames

#  [1] "Data/20260320_72hpf/Resaz_plate1_high_T0_260320_131142.xlsx" "Data/20260320_72hpf/Resaz_plate1_high_T1_260320_1424.xlsx"  
#  [3] "Data/20260320_72hpf/Resaz_plate1_high_T2_260320_1529.xlsx"   "Data/20260320_72hpf/Resaz_plate1_high_T3_260320_1640.xlsx"  
#  [5] "Data/20260320_72hpf/Resaz_plate1_high_T4_260320_1747.xlsx"   "Data/20260320_72hpf/Resaz_plate1_low_T0_260320_1328.xlsx"   
#  [7] "Data/20260320_72hpf/Resaz_plate1_low_T1_260320_1436.xlsx"    "Data/20260320_72hpf/Resaz_plate1_low_T2_260320_1542.xlsx"   
#  [9] "Data/20260320_72hpf/Resaz_plate1_low_T3_260320_1649.xlsx"    "Data/20260320_72hpf/Resaz_plate1_low_T4_260320_1758.xlsx"   
# [11] "Data/20260320_72hpf/Resaz_plate2_high_T0_260320_1316.xlsx"   "Data/20260320_72hpf/Resaz_plate2_high_T1_260320_1420.xlsx"  
# [13] "Data/20260320_72hpf/Resaz_plate2_high_T2_260320_1532.xlsx"   "Data/20260320_72hpf/Resaz_plate2_high_T3_260320_1637.xlsx"  
# [15] "Data/20260320_72hpf/Resaz_plate2_high_T4_260320_1743.xlsx"   "Data/20260320_72hpf/Resaz_plate2_low_T0_260320_1331.xlsx"   
# [17] "Data/20260320_72hpf/Resaz_plate2_low_T1_260320_1433.xlsx"    "Data/20260320_72hpf/Resaz_plate2_low_T2_260320_1544.xlsx"   
# [19] "Data/20260320_72hpf/Resaz_plate2_low_T3_260320_1653.xlsx"    "Data/20260320_72hpf/Resaz_plate2_low_T4_260320_1754.xlsx" 


resaz_15dpf_filenames <- list.files("Data/20260401_360hpf/", pattern = "\\.xlsx$", full.names = TRUE)
resaz_15dpf_filenames

# Read each file into a named list
xlsx_list_72hpf <- setNames(
                      lapply(resaz_72hpf_filenames, read_excel),
                      str_remove(basename(resaz_72hpf_filenames), "\\.xlsx$")
             )


xlsx_list_15dpf <- setNames(
                      lapply(resaz_15dpf_filenames, read_excel),
                      str_remove(basename(resaz_15dpf_filenames), "\\.xlsx$")
             )


```

```{r}
covert_to_df <- function (file_in) {
                          file_out <- as.data.frame(file_in[-c(1:26), -c(1,15)]) # drop first columns and first 26 rows
                          colnames(file_out) <- c("Plate_row", 1,2,3,4,5,6,7,8,9,10,11,12)
                          
                          file_out <- file_out %>%  
                              tidyr::pivot_longer(
                                cols = -Plate_row,
                                names_to = "Plate_col",
                                values_to = "flourescence"
                              ) %>% 
                            # dplyr::mutate(filename = x.2) %>% 
                            dplyr::mutate(timepoint = "T0", 
                                          plate = "1", 
                                          Well = paste0(Plate_row,Plate_col),
                                          time= as.POSIXlt((strptime(1311, format = "%H%M")),
                                                           format = "%H:%M")
                                                                                                 
                                          )
                          
                          return(file_out)
                        }

covert_to_df_2 <- function (file_in) {
                          file_out <- as.data.frame(file_in[-c(1:26), -c(1,15)]) # drop first columns and first 26 rows
                          colnames(file_out) <- c("Plate_row", 1,2,3,4,5,6,7,8,9,10,11,12)
                          
                          x.hrmin <- as.numeric(gsub("^.*_(\\d+)\\.xlsx$", "\\1", x))
                          file_out <- file_out %>%  
                              tidyr::pivot_longer(
                                cols = -Plate_row,
                                names_to = "Plate_col",
                                values_to = "flourescence"
                              ) %>% 
                            dplyr::mutate(filename = as.character(x.2)) %>% 
                            dplyr::mutate(timepoint = gsub("^.*?(T\\d+).*$", "\\1", x.2), 
                                          plate = gsub("^.*plate(\\d+).*", "\\1", x.2), 
                                          Well = paste0(Plate_row,Plate_col),
                                          time= as.POSIXlt((strptime(x.hrmin, format = "%H%M")),
                                                           format = "%H:%M")
                                                                                                 
                                          )
                          
                          return(file_out)
                        }

loop.df           <- data.frame(matrix(nrow = 1, ncol = 8)) # create dataframe to save cumunalitively during for loop
colnames(loop.df) <- c('filename', 'time', 'timepoint', 'Plate_row', 'Plate_col', 'Well', 'plate', 'flourescence') # names for columns in the for loop
rbind.df          <- data.frame() # start dataframe 
for (i in 1:length(resaz_15dpf_filenames)) {
  
 x         <- (basename(resaz_15dpf_filenames[i]))
 x.2       <- sub("\\.xlsx$", "", noquote(x))
 loop.df   <- covert_to_df_2(xlsx_list_15dpf[[x.2]])
 
 rbind.df <- rbind(rbind.df,
                     loop.df) #bind to a cumulative list dataframe
 print(rbind.df) # print to monitor progress
  
}


rbind.df <- rbind.df %>% 
                    dplyr::mutate(Date = 20260401,
                                  Treatment = dplyr::case_when(plate == 1 ~ "26C",
                                                        plate == 2 ~ "30C",
                                                        plate == 3 ~ "34C",
                                                        plate == 4 ~ "38C"),
                                  PlateID = dplyr::case_when(plate == 1 ~ "plate_1_26",
                                                        plate == 2 ~ "plate_2_30",
                                                        plate == 3 ~ "plate_3_34",
                                                        plate == 4 ~ "plate_4_38"))

all_data_merged <- dplyr::left_join(rbind.df,metadata_counts, by=c('Date','PlateID', 'Well', 'Plate_row', 'Treatment'))

```

```{r 72hpf plate 1}
plate1_high_T0_260320 <- covert_to_df(xlsx_list$Resaz_plate1_high_T0_260320_131142) %>% dplyr::mutate(timepoint = "T0", 
                                                                                                      plate = "1", 
                                                                                                      Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1311, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate1_high_T1_260320 <- covert_to_df(xlsx_list$Resaz_plate1_high_T1_260320_1424) %>% dplyr::mutate(timepoint = "T1", 
                                                                                                    plate = "1", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1424, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate1_high_T2_260320 <- covert_to_df(xlsx_list$Resaz_plate1_high_T2_260320_1529) %>% dplyr::mutate(timepoint = "T2", 
                                                                                                    plate = "1", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1529, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate1_high_T3_260320 <- covert_to_df(xlsx_list$Resaz_plate1_high_T3_260320_1640) %>% dplyr::mutate(timepoint = "T3", 
                                                                                                    plate = "1", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1640, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate1_high_T4_260320 <- covert_to_df(xlsx_list$Resaz_plate1_high_T4_260320_1747) %>% dplyr::mutate(timepoint = "T4", 
                                                                                                    plate = "1", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1747, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )
```

```{r 72 hpf plate 2}



plate2_high_T0_260320 <- covert_to_df(xlsx_list$Resaz_plate2_high_T0_260320_1316) %>% dplyr::mutate(timepoint = "T0", 
                                                                                                      plate = "2", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1316, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate2_high_T1_260320 <- covert_to_df(xlsx_list$Resaz_plate2_high_T1_260320_1420) %>% dplyr::mutate(timepoint = "T1", 
                                                                                                    plate = "2", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1420, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate2_high_T2_260320 <- covert_to_df(xlsx_list$Resaz_plate2_high_T2_260320_1532) %>% dplyr::mutate(timepoint = "T2", 
                                                                                                    plate = "2", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1532, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate2_high_T3_260320 <- covert_to_df(xlsx_list$Resaz_plate2_high_T3_260320_1637) %>% dplyr::mutate(timepoint = "T3", 
                                                                                                    plate = "2", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1637, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate2_high_T4_260320 <- covert_to_df(xlsx_list$Resaz_plate2_high_T4_260320_1743) %>% dplyr::mutate(timepoint = "T4", 
                                                                                                    plate = "2", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1743, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )
```

```{r}

plate1_low_T0_260320 <- covert_to_df(xlsx_list$Resaz_plate1_low_T0_260320_1328) %>% dplyr::mutate(timepoint = "T0", 
                                                                                                      plate = "1", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1328, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate1_low_T1_260320 <- covert_to_df(xlsx_list$Resaz_plate1_low_T1_260320_1436) %>% dplyr::mutate(timepoint = "T1", 
                                                                                                    plate = "1", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1436, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate1_low_T2_260320 <- covert_to_df(xlsx_list$Resaz_plate1_low_T2_260320_1542) %>% dplyr::mutate(timepoint = "T2", 
                                                                                                    plate = "1", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1542, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate1_low_T3_260320 <- covert_to_df(xlsx_list$Resaz_plate1_low_T3_260320_1649) %>% dplyr::mutate(timepoint = "T3", 
                                                                                                    plate = "1", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1649, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate1_low_T4_260320 <- covert_to_df(xlsx_list$Resaz_plate1_low_T4_260320_1758) %>% dplyr::mutate(timepoint = "T4", 
                                                                                                    plate = "1", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1758, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )
```

```{r}

plate2_low_T0_260320 <- covert_to_df(xlsx_list$Resaz_plate2_low_T0_260320_1331) %>% dplyr::mutate(timepoint = "T0", 
                                                                                                      plate = "1", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1331, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate2_low_T1_260320 <- covert_to_df(xlsx_list$Resaz_plate2_low_T1_260320_1433) %>% dplyr::mutate(timepoint = "T1", 
                                                                                                    plate = "1", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1433, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate2_low_T2_260320 <- covert_to_df(xlsx_list$Resaz_plate2_low_T2_260320_1544) %>% dplyr::mutate(timepoint = "T2", 
                                                                                                    plate = "1", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1544, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate2_low_T3_260320 <- covert_to_df(xlsx_list$Resaz_plate2_low_T3_260320_1653) %>% dplyr::mutate(timepoint = "T3", 
                                                                                                    plate = "1", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1649, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )

plate2_low_T4_260320 <- covert_to_df(xlsx_list$Resaz_plate2_low_T4_260320_1754) %>% dplyr::mutate(timepoint = "T4", 
                                                                                                    plate = "1", 
                                                                                                    Well = paste0(Plate_row,Plate_col),
                                                                                                    time= as.POSIXlt(
                                                                                                                    (strptime(1754, format = "%H%M")), 
                                                                                                                    format = "%H:%M")
                                                                                                 )
```

```{r}

plate1_high_master <- rbind(plate1_high_T0_260320, plate1_high_T1_260320, plate1_high_T3_260320, plate1_high_T4_260320) %>% 
                          dplyr::mutate(Date = 20260320,
                                        Treatment = 'high_temperature',
                                        PlateID = 'plate_1_high')

plate2_high_master <- rbind(plate2_high_T0_260320, plate2_high_T1_260320, plate2_high_T3_260320, plate2_high_T4_260320) %>% 
                          dplyr::mutate(Date = 20260320,
                                        Treatment = 'high_temperature',
                                        PlateID = 'plate_2_high')

plate1_low_master <- rbind(plate1_low_T0_260320, plate1_low_T1_260320, plate1_low_T3_260320, plate1_low_T4_260320) %>% 
                          dplyr::mutate(Date = 20260320,
                                        Treatment = 'low_temperature',
                                        PlateID = 'plate_1_low')

plate2_low_master <- rbind(plate2_low_T0_260320, plate2_low_T1_260320, plate2_low_T3_260320, plate2_low_T4_260320) %>% 
                          dplyr::mutate(Date = 20260320,
                                        Treatment = 'low_temperature',
                                        PlateID = 'plate_2_low')

all_data <- rbind(plate1_high_master, plate2_high_master, plate1_low_master, plate2_low_master)

all_data_merged <- merge(all_data,metadata_counts, by=c('Date','PlateID', 'Well'))

all_data_merged <- dplyr::left_join(all_data,metadata_counts, by=c('Date','PlateID', 'Well', 'Plate_row', 'Treatment'))


plate1_high_master_merged
```

```{r auc calc function}

output.df <- data.frame()
loop.df_m   <- data.frame(unique(rbind.df$PlateID))
loop.df_i   <- data.frame(unique(rbind.df$Well))


# Call the cumulative dataframe that we will write to in the for loop below
output.cumulative.df <- data.frame() # start dataframe 
output.df            <- data.frame() # start dataframe 
output.cor.df        <- data.frame() # start dataframe 
running.df           <- data.frame(matrix(nrow = 1, ncol = 9)) # create dataframe to save cumunalitively during for loop
colnames(running.df) <- c('Date', 'Treatment', 'PlateID', 'Age', 'Well', 'Family', 'Type', 'Count', 'AUC') # names for columns in the for loop

for(m in 1:nrow(loop.df_m)){
  plate_id      <- all_data_merged %>% 
                                dplyr::filter(PlateID %in% loop.df_m[m,1])
for(i in 1:nrow(loop.df_i)){
  well.over.time       <- plate_id %>% 
                                dplyr::filter(Well %in% loop.df_i[i,1]) %>% 
                                dplyr::arrange(time) %>% 
                                dplyr::mutate(hours = as.numeric(difftime(time, 
                                                                          time[1], 
                                                                          units = "hours")),
                                              delta_florescence = flourescence - flourescence[1],
                                              AUC = pracma::trapz(
                                                                  hours, 
                                                                  flourescence)) %>% 
                                dplyr::select('Date', 'Treatment', 'PlateID', 'Age', 'time', 'Family', 'hours',
                                              'Well', 'Type', 'Count', 'AUC', 'delta_florescence')
                      
  output.cumulative.df <- rbind(output.cumulative.df, well.over.time)
  
  running.df$Date      <- well.over.time$Date[1]
  running.df$Treatment <- well.over.time$Treatment[1]
  running.df$PlateID   <- well.over.time$PlateID[1]
  running.df$Age       <- well.over.time$Age[1]
  running.df$Well      <- well.over.time$Well[1]
  running.df$Family    <- well.over.time$Family[1]
  running.df$Type      <- well.over.time$Type[1]
  running.df$Count     <- well.over.time$Count[1]
  running.df$AUC       <- well.over.time$AUC[1]
  
   output.df <- rbind(output.df,
                     running.df) #bind to a cumulative list dataframe
   print(output.df) # print to monitor progress
   
   
   # mean.AUC.blanks <- mean(
   #                        (output.df %>% dplyr::filter(Type %in% 'Blank' & !AUC > 5400))$AUC
   # )
  
   output.cor.df <- output.df %>% 
                            dplyr::filter(!Type %in% 'Blank') %>% 
                            dplyr::mutate(AUC_cor      = as.numeric(AUC-mean.AUC.blanks),
                                          # AUC_cor_norm = AUC_cor/Count)
                                          AUC_cor_norm = dplyr::case_when(
                                                                          (AUC_cor < 0 | Count == 0) ~ NA,
                                                                          (AUC_cor > 0 & Count > 0) ~ AUC_cor/Count)) %>% 
                            na.omit()
                      
                           
  }
}

output.cor.df_final <- merge(plate_notes, output.cor.df) %>% 
                                                dplyr::mutate(Family_EBV = 
                                                   dplyr::case_when(Family > 50 ~ 'Low',
                                                              Family < 20 ~ 'High'))

output.cumulative.df <- merge(plate_notes, output.cumulative.df) %>% dplyr::mutate(Family_EBV = 
                                                   dplyr::case_when(Family > 50 ~ 'Low',
                                                              Family < 20 ~ 'High'))



output.cor.df_final_omit <- output.cor.df_final %>% 
                                dplyr::filter(!obs_volume %in% 'has no volume') #%>% 
                                #dplyr::filter(!Count < 10)

output.cumulative.df_omit <- output.cumulative.df %>% 
                                dplyr::filter(!obs_volume %in% 'has no volume') #%>% 
                                #dplyr::filter(!Count < 10)

delta_abs_figure <- ggplot(
          (output.cumulative.df_omit %>% dplyr::filter(!(Type == 'Sample' & Count == 0))),
           aes(hours, delta_florescence, group = Well)) +
      # geom_point(aes(color = Type)) +
      geom_smooth(aes(color = Type), method = "lm", se = FALSE) +
  facet_wrap(~Treatment,scales = "free")
delta_abs_figure


AUC_cor_by_count <- ggplot(output.cor.df_final_omit, 
                aes(x = Count, y = AUC_cor,  color = Family_EBV)) +
  geom_point(fill = "steelblue")+
  facet_wrap(~Treatment,scales = "free")
AUC_cor_by_count

summary.df <- Rmisc::summarySE(
                      data = (output.cor.df),
                      groupvars = c('Family', 'Treatment'),
                      measurevar = 'AUC_cor_norm')

summary.df <- summary.df %>% dplyr::mutate(Family_EBV = 
                                                   dplyr::case_when(Family > 50 ~ 'Low',
                                                              Family < 20 ~ 'High'))

AUC_cor_by_count_fam <- ggplot(summary.df, 
                aes(x = as.factor(as.numeric(Family)), y = AUC_cor_norm, color = Family_EBV)) +
  geom_point(fill = "steelblue") +
  geom_errorbar(aes(ymin = AUC_cor_norm - se, ymax = AUC_cor_norm + se), width = 0.2) +
  theme_classic() +
  facet_wrap(~Treatment,scales = "free")


AUC_cor_by_count_fam <- ggplot(summary.df, 
                aes(x = Treatment, y = AUC_cor_norm, group = as.factor(as.numeric(Family)), color = Family_EBV)) +
  geom_point(fill = "steelblue") +
  geom_smooth(method = "loess", se = TRUE) +
  # geom_errorbar(aes(ymin = AUC_cor_norm - se, ymax = AUC_cor_norm + se), width = 0.2) +
  theme_classic() + 
  facet_wrap(~Family_EBV)


# ?facet_wrap
ggarrange(delta_abs_figure,
          AUC_cor_by_count,
          AUC_cor_by_count_fam,
          nrow=3,
          ncol=1)

```


plate2_high_master <- rbind(plate2_high_T0_260320, plate2_high_T1_260320, plate2_high_T3_260320, plate2_high_T4_260320)

high_master <- rbind(plate1_high_master, plate2_high_master) %>% 
                     dplyr::mutate(EBV_cat = 
                                     case_when(column_id %in% c("col1", "col2", "col3", "col4", "col5", "col6") ~ 'Low',
                                               column_id  %in% c("col7", "col8", "col9", "col10", "col11", "col12") ~ 'High'))
                                      


```{r}
high_master_summ  <- Rmisc::summarySE(
                                data = (high_master %>% dplyr::filter(!Row %in% 'H')),
                                measurevar = "flourescence",
                                groupvars = c("column_id", "time" , "EBV_cat")
                             )

```

```{r}
blank_master_summ  <- Rmisc::summarySE(
                                data = (high_master %>% dplyr::filter(Row %in% 'H')),
                                measurevar = "flourescence",
                                groupvars = c("time")
                             )

```


```{r}
library(ggplot2)
ggplot(test, 
       aes(x = time, y = flourescence, group=Well)) +
  geom_point(size = 3) +
  geom_line()+
  geom_errorbar(aes(ymin = flourescence_cor - se, ymax = flourescence_cor + se),
                width = 0.15) +
  geom_smooth(method = "loess", se = FALSE) +
  theme_classic() # +
  # facet_wrap(~column_id)

```

```{r}
ggplot(blank_master_summ, 
       aes(x = time, y = flourescence)) +
  geom_point(size = 3) +
  geom_line()+
  geom_errorbar(aes(ymin = flourescence - se, ymax = flourescence + se),
                width = 0.15) +
  geom_smooth(method = "loess", se = FALSE) +

```